### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by sghaleb1** [benawad/redux-forms-example-weather#1]
Hello,
I have seen your YouTube videos regarding Redux-Saga which was very helpful. I was looking at your repo to learn more about Redux-Saga especially how to pass parameters from component to the API. But I cannot find the actionCreators.js file as it seems to be empty.
Is there a chance to upload it, if that is possible?
Many thanks!

**Comment by benawad** [comment]
I don't have the project locally anymore, so your best bet is to get the contents from the video
